#%RAML 1.0 NamedExample

  [{
                "categoryID" : 231,
                "name": "Laptop",
                "location": "room1",
                "quantity" : 70
              },
                {
                 "categoryID" : 2411,
                "name": "phones" ,
                "location": "room2",
                "quantity" : 50
                 },
               {
                 "categoryID" : 1556,
                "name": "tv" ,
                "location": "room3",
                "quantity" : 40
               }

              ]