#%RAML 1.0 NamedExample
[
  {
         "orderID": 1234,
         "userId": 12344,
         "name" : "Dell",
         "date": "2021-12-23",
         "status": "pending"
       },

  {
         "orderID": 1122,
         "userId": 254,
         "name" : "TV",
         "date": "2022-01-23",
         "status": "shipping"
       }      
]