#%RAML 1.0 NamedExample

  {
                  "productID": 1,
                  "categoryID": 10,
                  "name": "HP",
                  "description": "cor I 7",
                  "video_url": "www.hp.com",
                  "price": 7000
              } 